### ISSUE TITLE
transformation is taking too long

### ISSUE THREAD

**Issue by knasim** [alyssaq/hough_transform#2]
width, height = img.shape   ( this returns tuple of 3)  how are you expecting only 2 ?  
according to my calculation this loo shall run approx. 3 million times (too long)

```
  for i in range(len(x_idxs)):
    x = x_idxs[i]
    y = y_idxs[i]

    for t_idx in range(num_thetas):
      #print("looping ", t_idx)
      rho = round(x * cos_t[t_idx] + y * sin_t[t_idx]) + diag_len
      accumulator[rho.astype(np.uint64), t_idx] += 1
```

**Comment by alyssaq** [comment]
The jpg black values were showing up as `1` values rather than `0` and so the entire image became the search space. I've added a minimum threshold value to ignore values <5 in https://github.com/alyssaq/hough_transform/commit/5114918e6e060b85d0d14be56591318155fde4ba and it should finish much faster.
Please do try it out 😄

**Comment by knasim** [comment]
@alyssaq  - thanks I'll give it shot and let you know.

**Comment by iphton** [comment]
@alyssaq  hello, in your post, you have not discussed threshold. What's the use of it? Is it used to reduce noise for applying blur after implementing it? However, computation time is taking so long time. Can you explain it briefly?
